name: custom_scratch_card
description: A customizable scratch card widget for Flutter with reveal percentage and callback support.
version: 0.0.1

homepage: https://github.com/namitha-ttechlab/custom_scratch_card
repository: https://github.com/namitha-ttechlab/custom_scratch_card
issue_tracker: https://github.com/namitha-ttechlab/custom_scratch_card/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - scratch
  - animation
  - widget
  - flutter